# Generated by Django 4.1.2 on 2022-10-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Email', models.EmailField(max_length=500, unique=True)),
                ('Username', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
